### ISSUE TITLE
Feature request: How about an event for making the image object accessible

### ISSUE THREAD

**Issue by idw-git** [AngusJohnson/Image32#10]
I'm sorry for not finding a more proper subject for this, Angus, but here's what I was looking for, what I aready tried, and why I'm asking for an additional event:

1. First thing was my intention to access the TPngImage object for adjusting its compression level since it might not be desirable to use compression in certain situations, for a discussion about this cf. [here](https://en.wikipedia.org/wiki/Portable_Network_Graphics#File_size_factors).
2. Next I took a look at your _subclassing_ feature as provided using the TImageFormat() class: Now here I may be wrong, but I couldn't get it to work without apparently having to provide a completely rewritten (resp. copied) image format class since I never got to the point where registering a class derived from an existing one would replace the already existing one since the registering routine immediately exits if it detects an attempt to register the new one for replacing an already existing one. IOW: Since the inherited ancestor class is always registered before registering the derived one there's currently no way to replace it - or am I doing something wrong here?
3. So finally, that's why I'm coming up to make my suggestion: If the "subclassing" cannot achieve what I'm looking for, how about implementing a final OnSaveToStream() event exposing the TPngImage object (and similar for any other image type) for applying further type specific options without creating the need for you to provide various different access points depending on the respective image type's capabilities?

PS: For now I've just added a single line setting the desired compression level directly into your code, but that's note really the way I would prefer if there's a better one to be shared ...

					Michael

-- 
PGP Key ID (RSA 2048): 0xC45D831B
IERenderer's Home <https://www.pmpgp.de/renderer/History.htm>
S/MIME Fingerprint: 94C6B471 0C623088 A5B27701 742B8666 3B7E657C

**Comment by AngusJohnson** [comment]
Hi again Michael and thank you for the helpful feedback.

> Since the inherited ancestor class is always registered before registering the derived one there's currently no way to replace it - or am I doing something wrong here?

This seems to be the key issue. 
If I changed format registrations so that later registrations of the same format replace the existing one, then wouldn't that should solve this for you?

**Comment by idw-git** [comment]
> If I changed format registrations so that later registrations of the same format replace the existing one, then wouldn't that solve this for you?

I think so, don't ask me why I didn't give it a try, I certainly should have. The only important issue would be to make sure that no further initialization routines are affected to begin with which cannot easily be undone during replacement. Otherwise it should work, I assume. I'll get back to you after doing some more tests with regard to my original goal.
