### ISSUE TITLE
missing glyphs in text-on-path.svg

### ISSUE THREAD

**Issue by tomwiel** [AngusJohnson/Image32#101]
The red text draws empty boxes.
Previous versions showed cyrillic glyphs.

**Comment by AngusJohnson** [comment]
The `ParseNextWordExHash` function in `Img32.SVG.Core.pas` has a bug, and the fix is to delete the following line...

https://github.com/AngusJohnson/Image32/blob/5d05489e7601f6c751ca4888294af252b61d6dc5/source/Img32.SVG.Core.pas#L844

(I'll upload a new revision shortly.)

**Comment by tomwiel** [comment]
About the second issue, I'm not sure what the requirements are. IsSameUTF8String(), IsSameAsciiUTF8String() seem to expect s1 being lower case and s2 any case. One solution would be changing the case-statement to:  `case ch2 of 'A'..'Z': ch2 := UTF8Char(Ord(ch2) xor $20);` Or adding the line, if required for both characters.

**Comment by ahausladen** [comment]
The comments in IsSameUTFString and IsSameAsciiUTF8String say "toggle upper/lower", but the code I wrote only toggled the upper characters to lower. Thanks for fixing this and all the other bugs that I introduced.

**Comment by AngusJohnson** [comment]
And thanks for all your hard work too Andreas. I've added a brief acknowledgement of your contribution in the documentation. I hope that's ok.
