### ISSUE TITLE
Incorrect draw of rounded corners

### ISSUE THREAD

**Issue by carloBarazzetta** [AngusJohnson/Image32#106]
I've notice this problem with the file attached:
![Button_error](https://github.com/user-attachments/assets/0779c118-aec4-40a6-b9cb-f83b281bede9)
![OK_GRAPH_BUTTON](https://github.com/user-attachments/assets/85dea7cb-c9f9-4890-891b-6407ec8d6fe7)
The error was introduced from 22 May 2024 to 18 July 2024...

**Comment by ahausladen** [comment]
Looks like commit 996f5306f60b06fc79b4716b3257aec08fefb84a (2024-06-21) is the cause for this, that was made to fix issue #62.

**Comment by AngusJohnson** [comment]
Hopefully fixed now.

**Comment by carloBarazzetta** [comment]
Thank you very much!
