### ISSUE TITLE
SVGImage Small font size dont render properly, size less than 8px

### ISSUE THREAD

**Issue by mahmoudikia** [AngusJohnson/Image32#11]
texts on svg with font size less than 8px don't render properly and nothing is shown in screen

**Comment by AngusJohnson** [comment]
I'm not seeing any problems. See the attached sample app that displays the attached image
[image32_test.zip](https://github.com/AngusJohnson/Image32/files/9786468/image32_test.zip)
![test](https://user-images.githubusercontent.com/5280692/195852812-a92aacc7-b4cb-44b0-9889-8c26a5c8a601.svg)
