### ISSUE TITLE
Problem with rendering emoji SVG files

### ISSUE THREAD

**Issue by PeterPanino** [AngusJohnson/Image32#111]
Hi, these SVG files are displayed without problems in any browser:

[SVG.zip](https://github.com/user-attachments/files/17666762/SVG.zip)

Why can Image32 not render them?

This is not a font issue, as the 'Segoe UI Emoji' is present on my system.

**Comment by andersmelander** [comment]
See  #80
TLDR; There's no support for Emoji fonts.

**Comment by PeterPanino** [comment]
But ImageEn can render these SVGs without problems:

https://www.imageen.com

**Comment by andersmelander** [comment]
Did you have a point?

**Comment by PeterPanino** [comment]
I am referring to an issue, and you reply: "Did you have a point?"

**Comment by andersmelander** [comment]
> I am referring to an issue, and you reply: "Did you have a point?

You did not "refer to an issue"; You stated:

> But ImageEn can render these SVGs without problems

and I asked what your point was with _that_ statement. It isn't a hard question.

You have asked why the library can't render your SVGs and I have explained the reason why; It doesn't support Emoji fonts and, as the linked issue states, it will not support them.
