### ISSUE TITLE
Double line path glitch

### ISSUE THREAD

**Issue by andrey7418** [AngusJohnson/Image32#12]
Tried to render SVG with a single path consisted of one long and one short lines:
`<path d="m 160,720 h 120 v 0.025" style="stroke: #000000;" />`
   and got an unexpected result:
![image](https://user-images.githubusercontent.com/115896123/196003548-100e8595-e931-48d0-8940-05c7229cb6e7.png)

while rendering almost the same path:
`<path d="m 160,720 h 120 v 0.028" style="stroke: #000000;" />`
is ok and looks like this:
![image](https://user-images.githubusercontent.com/115896123/196003616-126d9ac0-042f-48c1-b021-27a5e45b0bc0.png)

The whole SVG file is:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   width="800"
   height="800"
   viewBox="0 0 800 800"
>

<path d="m 160,720 h 120 v 0.025" style="stroke: #000000;" />
   
</svg>

```

**Comment by AngusJohnson** [comment]
Thanks. This should be fixed now in the latest commit.
