### ISSUE TITLE
Why did Resource Hacker 5.1.8 got reverted to 5.1.7?

### ISSUE THREAD

**Issue by jpluimers** [AngusJohnson/Image32#14]
Asking here as this repository is probably what [Resource Hacker](http://www.angusj.com/resourcehacker/) is based on.

https://web.archive.org/web/20221224133731/http://www.angusj.com/resourcehacker/ now has version 5.1.7 first archived as https://web.archive.org/web/20190103025235/http://angusj.com/resourcehacker (downloadable as [EXE install](https://web.archive.org/web/20190103025235/http://angusj.com/reshacker_setup.exe) and [ZIP install](https://web.archive.org/web/20190103025235/http://angusj.com/resource_hacker.zip))

Up until https://web.archive.org/web/20221107224420/http://www.angusj.com/resourcehacker/ version 5.1.8 was available (downloadable as [EXE install](https://web.archive.org/web/20221107224420/http://www.angusj.com/resourcehacker/reshacker_setup.exe) and [ZIP install](https://web.archive.org/web/20221107224420/http://www.angusj.com/resourcehacker/resource_hacker.zip))

Why after almost 4 years the reversal?

**Comment by jpluimers** [comment]
I checked again:

- the web-site text is wrong mentioning 5.1.7 as the downloads are 5.1.8.360
- http://www.angusj.com/resourcehacker/reshacker_setup.exe and https://web.archive.org/web/20221107224420/http://www.angusj.com/resourcehacker/reshacker_setup.exe are the same and install version 5.1.8.360 but present themselves asl 0.0.0.0 which is odd (most installers embedding the software to be installed I have seen contain the same version number as the software they install)
- http://www.angusj.com/resourcehacker/resource_hacker.zip and https://web.archive.org/web/20221107224420/http://www.angusj.com/resourcehacker/resource_hacker.zip both contain version 5.1.8.360

I think it is worth both fixing the web-site text and installer version.

**Comment by jpluimers** [comment]
Hi @AngusJohnson, 

Sorry for getting back this late. I got some health problems and problems in the family at the same time, so I was a bit occupied the last 3 months.

In the meantime you closed this issue without an answer but also without resolving the web-page at http://www.angusj.com/resourcehacker/ which still mentions version 5.1.7 while the actual downloads are 5.1.8.360.

Can you please re-open this issue or fix the web-site?

It would be cool if you could also update the http://www.angusj.com/resourcehacker/reshacker_setup.exe in include a VersionInfo resource presenting itself as 5.1.8.360 instead of the current 0.0.0.0.

Regards,

--jeroen

**Comment by AngusJohnson** [comment]
HI Jeroen.
Firstly, I'm very sorry about your health and family problems. I do hope they have resolved or at least improved.

> In the meantime you closed this issue without an answer 

That's because Resource Hacker has nothing to do with my Image32 library, or this forum.
I do understand that there's no forum for RH so there's nowhere to post requests etc for it anywhere.
And That's deliberate because I have no plans to update to RH. 
I'll note your request and may get around to fixing the issues you've raised here, but currently I'm fully occupied with other things. Sorry.

**Comment by jpluimers** [comment]
Hi @AngusJohnson ,

Thank a lot for getting back!
I'm still alive, which is way better than expected and the family thing is slowly resulting in not having to worry about us providing some ~20 hours/week of care anymore and even better: good care after I will inevitably pass away.
All in all good things, so hopefully I'll be able to pick up Delphi and .NET work later this year again.

So thanks again for putting this on your list of things to fix. Looking forward to it, but no hurries.

Regards,

--jeroen
