### ISSUE TITLE
Resize() produces wrong size

### ISSUE THREAD

**Issue by tweibert** [AngusJohnson/Image32#15]
Hello,

I have found that the `Resize()` method, depending on the original and requested size, does not always produce an image of the request sized, but 1 pixel wider and/or higher.

It only happens when using one of the resamplers, e.g. the bilinear or bicubic one. 

Here is some code to demonstrate the issue:

````delphi
program Test1;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  System.SysUtils,
  Img32;

var
  img: TImage32;

begin
  try
    img := TImage32.Create(225, 225);
    try
      img.Resize(122, 122);

      WriteLn(Format('New size: %d / %d', [img.Width, img.Height])); // wrong: 123 / 123
    finally
      img.Free;
    end;

    img := TImage32.Create(225, 225);
    try
      img.Resampler := 0;
      img.Resize(122, 122);

      WriteLn(Format('New size: %d / %d', [img.Width, img.Height])); // correct: 122 / 122
    finally
      img.Free;
    end;

    Readln;
  except
    on E: Exception do
      Writeln(E.ClassName, ': ', E.Message);
  end;
end.
````

I stepped through the code, and it appears that it is caused by rounding errors when going back to integer coordinates in `GetBounds()`:

````delphi
function GetBounds(const path: TPathD): TRect;
var
  recD: TRectD;
begin
  recD := GetBoundsD(path);
  Result := Rect(recD);
end;
````

In the above example, the calculated height and width (as `Double`) is just slightly larger than 122, so that `Ceil()` turns it into 123:

````delphi
function Rect(const recD: TRectD): TRect;
begin
  Result.Left := Floor(recD.Left);
  Result.Top := Floor(recD.Top);
  Result.Right := Ceil(recD.Right);
  Result.Bottom := Ceil(recD.Bottom);
end;
 ````

The fact that `Resize()` does not work as expected  causes trouble in other parts of the library. In particular, `ScaleToFitCentered()` assumes that the temporary resized image it creates has exactly the requested size, which it has not, and then `CopyInternal()` will corrupt the RAM by copying more pixels from the source than the destination can hold.

**Comment by tweibert** [comment]
This is how I use `IntersectRect()` to work around the RAM corruption issue in `ScaleToFitCentered()`. It shrinks the Rect so that it is never larger than the total image size. This may result in the image being cropped by 1 pixel, but at least it doesn't write beyond the actual size of the Pixels array anymore:

````delphi
procedure TImage32.ScaleToFitCentered(width, height: integer);
var
  sx, sy: double;
  tmp: TImage32;
  rec2: TRect;
begin
  if IsEmpty or (width <= 0) or (height <= 0) or
    ((width = self.Width) and (height = self.Height)) then Exit;

  sx := width / self.Width;
  sy := height / self.Height;
  BlockNotify;
  try
    if sx <= sy then
    begin
      Scale(sx);
      if height = self.Height then Exit;
      rec2 := Bounds;
      Types.OffsetRect(rec2, 0, (height - self.Height) div 2);
      Types.IntersectRect(rec2, rec2, Types.Rect(0, 0, width, height)); // workaround for bug in Resize()
      tmp := TImage32.Create(self);
      try
        SetSize(width, height);
        CopyInternal(tmp, tmp.Bounds, rec2, nil);
      finally
        tmp.Free;
      end;
    end else
    begin
      Scale(sy);
      if width = self.Width then Exit;
      rec2 := Bounds;
      Types.OffsetRect(rec2, (width - self.Width) div 2, 0);
      Types.IntersectRect(rec2, rec2, Types.Rect(0, 0, width, height)); // workaround for bug in Resize()
      tmp := TImage32.Create(self);
      try
        SetSize(width, height);
        CopyInternal(tmp, tmp.Bounds, rec2, nil);
      finally
        tmp.Free;
      end;
    end;
  finally
    UnblockNotify;
  end;
  Resized;
end;
````

Alternatively, I could have added `IntersectRect()` straight into `CopyInternal()`, but as the code says it's an "internal routine that has no scaling or bounds checking" (which is true!), I figured it might be favorable to pass a valid rect in the first place.

Hope this workaround will help other people until `Resize()` is eventually fixed.

**Comment by AngusJohnson** [comment]
Thanks. I hope to look at and fix this issue in the coming week.

**Comment by AngusJohnson** [comment]
Hopefully fixed now 😁.
