### ISSUE TITLE
GetCompositeGlyph Result?

### ISSUE THREAD

**Issue by ericlangedijk** [AngusJohnson/Image32#18]
in the function "TFontReader.GetCompositeGlyph" nothing seems to be done with the Result var.

and thus:
if Result <> nil then
          AffineTransform(a,b,c,d,e,f, result);
seems to me as a statement that is never executed.

Is this indeed "wrong" or do I overlook something?

**Comment by AngusJohnson** [comment]
Hi Eric.

> or do I overlook something?

I think so 😁.

`GetCompositeGlyph` is called in and returned by `GetGlyphPaths`, and that result is used by several methods.
