### ISSUE TITLE
#delphi, #pascal

### ISSUE THREAD

**Issue by LingamYoni** [AngusJohnson/Image32#2]
Could you please add **delphi** and **pascal** tags? Without them, your GitHub repository not listing in search, for instance: https://github.com/topics/delphi?o=desc&s=updated
![i32](https://user-images.githubusercontent.com/40486018/174238598-2842b204-18bd-41ed-928d-2446bdf0b6d7.png)

**Comment by AngusJohnson** [comment]
Thanks. I'll do that now. 👍😁

**Comment by AngusJohnson** [comment]
Just got to figure out how 🤪

**Comment by LingamYoni** [comment]
> Just got to figure out how 🤪

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics
