### ISSUE TITLE
TImageFormat_SVG SaveToStream declaration differs from the base class 

### ISSUE THREAD

**Issue by albertofll** [AngusJohnson/Image32#20]
Compiling the library i get this error in unit Img32.Fmt.SVG

procedure SaveToStream(stream: TStream; img32: TImage32); override;

procedure SaveToStream(stream: TStream; img32: TImage32; quality: integer = 0); override;  base class

**Comment by AngusJohnson** [comment]
Thanks. I'll fix this ASAP.
