### ISSUE TITLE
Incorrect interpretation of USE_MY_METRICS

### ISSUE THREAD

**Issue by andersmelander** [AngusJohnson/Image32#24]
https://github.com/AngusJohnson/Image32/blob/4e2ba14853d43906a7e055b53490b5cc660df203/source/Img32.Text.pas#L1885-L1890

It is my understanding that the `USE_MY_METRICS` flag has nothing to do with the path transformation. As I read it, if a child glyph has the `USE_MY_METRICS` flag set it means that the parent glyph should use the **metrics** of the flagged child glyph. The metrics being the left side-bearing, right side-bearing, and advance width.
The Apple docs aren't very clear on this. The Microsoft docs are a bit better - but not much.

**Comment by AngusJohnson** [comment]
Hopefully fixed now.

**Comment by AngusJohnson** [comment]
Thanks again Anders for your valuable feedback. 
It's been quite a while since I've closely looked at this stuff so I'm rather rusty about this now. I might look at this more closely soonish, but at the moment I'm occupied with other things, including improving the vectorization and color quantization code here. 
Regarding  implementing point-to-point positioning and hmtx and vmtx: if you can provide code that implements these, or links to where these are implemented elsewhere, I would of course fix this more quickly 😁🤞.

**Comment by andersmelander** [comment]
> The problem is that you're only getting the metrics of the root GlyphID. What you need to do is get the metrics of each component (potentially) all the way down the tree.

I ended up taking a different approach which I like much better: Instead of passing the metric structure around, I simply implemented a GetGlyphMetric method that internally traverses the glyph tree to find the GlyphID which will supply the metric. Since it doesn't need to traverse the whole tree it's actually pretty efficient. It goes something like this:

```pascal
function TRedacted.GetGlyphMetric(GlyphIndex: Word): TTrueTypeGlyphMetric;
var
  GlyphDataTable: TTrueTypeFontGlyphDataTable;

  procedure DoGetGlyphMetric(GlyphIndex: Word; var MetricIndex: Word);
  var
    Glyph: TCustomTrueTypeFontGlyphData;
    i: integer;
    CompositeGlyphData: TTrueTypeFontCompositeGlyphData;
    ComponentGlyphMetric: TTrueTypeGlyphMetric;
  begin
    Glyph := GlyphDataTable.GlyphData[GlyphIndex];

    // If glyph is a simple glyph then we will just use its index as the metric index.
    if (Glyph is TTrueTypeFontSimpleGlyphData) then
      // The default MetricIndex value has already been set by the caller.
      exit;

    // If glyph is a composite glyph, then we will either use its index or one of
    // its components index as the metric index.
    if Glyph is TTrueTypeFontCompositeGlyphData then
    begin
      // The default MetricIndex value has already been set by the caller.
      CompositeGlyphData := TTrueTypeFontCompositeGlyphData(Glyph);

      // Recursively process composite glyph components
      for i := 0 to CompositeGlyphData.GlyphCount-1 do
        if (CompositeGlyphData.Glyph[i].Flags and TRedactedCompositeGlyph.GLYF_USE_MY_METRICS <> 0) then
        begin
          // We will use the index of the component. Set MetricIndex and recurse.
          MetricIndex := CompositeGlyphData.Glyph[i].GlyphIndex;

          DoGetGlyphMetric(CompositeGlyphData.Glyph[i].GlyphIndex, MetricIndex);

          // In theory multiple components could set USE_MY_METRICS but we
          // ignore that as it doesn't make sense.
          exit;
        end;
    end;
  end;

var
  MetricIndex: Word;
  VerticalMetricsTable: TRedactedVerticalMetricsTable;
begin
  Result := Default(TTrueTypeGlyphMetric);
  GlyphDataTable := TTrueTypeFontGlyphDataTable(GetTableByTableName('glyf'));
  if (GlyphDataTable = nil) then
    exit;

  MetricIndex := GlyphIndex;
  DoGetGlyphMetric(GlyphIndex, MetricIndex);

  Result.HorizontalMetric := FHorizontalMetrics.HorizontalMetric[MetricIndex];

  VerticalMetricsTable := TRedactedVerticalMetricsTable(GetTableByTableType(TRedactedVerticalMetricsTable.GetTableType));
  if (VerticalMetricsTable <> nil) then
    Result.VerticalMetric := VerticalMetricsTable.VerticalMetric[MetricIndex];
end;
```


> Regarding implementing point-to-point positioning and hmtx and vmtx

Point-to-point position is pretty easy and the documentation is clear on how it's done. Unfortunately, a key part of that feature is "phantom points" and the details of those seem to be completely undocumented. I know what they represent (the four "corners" of the glyph), but apart from that it's pretty much guesswork.
I have also been unable to find any glyphs that actually use this feature so I'm concentrating on more important stuff for now.
