### ISSUE TITLE
Refresh Bug - Layer 301 example

### ISSUE THREAD

**Issue by sternbach** [AngusJohnson/Image32#29]
Hi Angus, 

it seems that there's a refresh problem when you have several nested group layers. The problem can be reproduced.
The problem occurs when a layer moves outside the bounds of the parent layer. 

Have a look at the video:

https://github.com/AngusJohnson/Image32/assets/91251599/a5c523e0-57f2-4c4e-875b-3e4afae189c4

and 

https://github.com/AngusJohnson/Image32/assets/91251599/fb77a8b8-b14e-4eec-9973-da1216338e50

No clue at the moment what leads to the 2nd situation.

Cheers,
Peter

**Comment by AngusJohnson** [comment]
Hi Peter. Thanks for the feedback (and I've just seen and replied to your email too 😁).
I'll have a look at this as soon as I can, but it still might be a week or two. (I'm currently tied up with other things 😱).

**Comment by AngusJohnson** [comment]
Here's a partial fix...
Replace:
https://github.com/AngusJohnson/Image32/blob/bf28e286af2cb16f1c97be16acae219d64028308/source/Img32.Layers.pas#L805-L810
with:
```
procedure TLayer32.PositionAt(x, y: double);
var
  layer: TLayer32;
begin
  if (fLeft = x) and (fTop = y) then Exit;
  fLeft := x; fTop := y;
  layer := Parent;
  while Assigned(layer) and not (layer is TGroupLayer32) do
  begin
    layer.UpdateInfo.childUpdating := true;
    layer := layer.Parent;
  end;
  Invalidate;
end;
```

**Comment by AngusJohnson** [comment]
I'm hopeful that this is all fixed now.

**Comment by sternbach** [comment]
Thank you so muchg Angus!

Don't work too much on weekends... (written from my office haha)

mit besten Grüßen,

kind Regards,



*Peter Wichenthaler-Sternbach*

Geschäftsführer / CEO



Dr.-Anton-Schneider-Str.28b

6850 Dornbirn

Austria

phone: +43 (0) 5572 89 00 41

mobile: +43 (0)  664 883 98 555

***@***.***

***@***.***





Am So., 3. Sept. 2023 um 03:41 Uhr schrieb Angus Johnson <
***@***.***>:
