### ISSUE TITLE
Glitch when resizing TBitmap

### ISSUE THREAD

**Issue by Escain** [AngusJohnson/Image32#30]
Hello, 

I am trying to use Image32 to scale images in our application. After integrating the library, I am facing some glitches on the resulting TBitmap with transparency.

The full question is described here: https://stackoverflow.com/questions/76818048/resizing-tbitmap-with-alpha-channel-in-delphi

Simplified, the code looks like :

``````
function scaleBitmap( inPict: TPicture; scale: TSize; newRect: TRect ) : TPicture
begin
  var inBitmap: TImage32 := TImage32.Create;
  var outBitmap: TBitmap := TBitmap.Create;

  try
    inBitmap.CopyFromBitmap(inPict.Bitmap);

    inBitmap.Resampler := rBicubicResampler;
    inBitmap.Resize(scale.Width, scale.Height); // New size
    inBitmap.Crop(newRect); // Take only the required part.

    outBitmap.PixelFormat := pf32bit; // I think it's not required
    inBitmap.CopyToBitmap(Result); //Assume already created.
  finally
    FreeAndNil(inBitmap);
    FreeAndNil(outBitmap);
  end;
end
  ``````
  
 We have to interact with other components, that is why we use TBitmap and not TImage32 as the result. 
  
 The resulting image is scaled correctly, but alpha channel seems incorrect:
 
Original: 
![2vlDd](https://github.com/AngusJohnson/Image32/assets/10837802/c85c28cf-32a3-4c68-80c3-b3f30d7360c0)

Scaled:
![Pj9YH](https://github.com/AngusJohnson/Image32/assets/10837802/645b0ebf-95c9-4396-b953-c63fb4842038)

**Comment by AngusJohnson** [comment]
The following looks fine to me, though I don't really understand why you're bothering with both TImage32 and TBitmap.
I suggest you just stick with Image32 😁.

```
    var
      img: TImage32;
      bmp: TBitmap;
    begin
      
      img := TImage32.Create;
      bmp := TBitmap.Create;
    
      // use img to load the PNG file
      img.LoadFromFile('c:\temp\temp.png');
      // copy the image to a TBitmap
      img.CopyToBitmap(bmp);
      bmp.SaveToFile('c:\temp\temp.bmp');
      // verify that the copied image still looks OK as a saved BMP image
    
      // now clear img so there's no doubt that 
      // the following CopyFromBitmap() step is working
      img.Clear;
      img.CopyFromBitmap(bmp);
    
      // now scale the image using 'img'
      img.Resampler := rBicubicResampler;
      img.Scale(2.0);
    
      // copy scaled image back to the TBitmap
      img.CopyToBitmap(bmp);
      // and save rescaled image to another BMP file
      bmp.SaveToFile('c:\temp\temp2.bmp');
    
      // clean up
      bmp.Free;
      img.Free;
```

**Comment by AngusJohnson** [comment]
When you have the sorts of problems your having now, it's important to simplify the steps as much as possible so you don't assume the issue is in one particular area. And that's why I posted the code above, since I strongly suspect your problem is elsewhere. And I'm busy with other things so, rather than me debugging this for you, I suggest you do the following:
Save the bitmap image just before and just after resizing to a temporary files (eg bmp1.bmp and bmp2.bmp). 
Only then, if (when using an external image viewer) the second saved image still doesn't look accurately resized, that's very considerably narrowed done the issue.

**Comment by Escain** [comment]
The images saved by your code also look bad.
I think you used a png without transparency and that is why you don't see the issue.

**Comment by AngusJohnson** [comment]
I just used the PNG image that you provided. 
Nevertheless I've also tested this with transparent PNG images, and it's still OK.

```
  img := TImage32.Create;
  img.LoadFromFile('c:\temp\test2.png');
  bmp := TBitmap.Create;
  img.CopyToBitmap(bmp);
  bmp.SaveToFile('c:\temp\test2_pre.bmp');
  img.Clear;
  img.CopyFromBitmap(bmp);
  img.Resampler := rBicubicResampler;
  img.Scale(2.0);
  img.CopyToBitmap(bmp);
  bmp.SaveToFile('c:\temp\test2_post.bmp');
  bmp.Free;
  img.Free;
```

![test1](https://github.com/AngusJohnson/Image32/assets/5280692/0667f966-1415-4ac3-adae-2037beb12fb7)

![test2](https://github.com/AngusJohnson/Image32/assets/5280692/77f1e72c-10fa-40fd-9c6b-9e5169ff4a10)

**Comment by AngusJohnson** [comment]
> The background of your "X"/Close png is white

No it's not. I presume whatever app you're using to view this image has a default white background. Change the default transparency background to another color. Alternatively, click on this "X" image above and it'll display the image in a new tab window (which in Chrome at least is usually black). 

Anyhow, I've spent more than enough time on this now. Sorry I can't help further.

**Comment by AngusJohnson** [comment]
OK, one last try...

You're evidently doing something wrong with your image **rendering** (ie display).

This is your PRESCALED image from your post above:
![test2](https://user-images.githubusercontent.com/10837802/265722277-09a599cb-3039-458a-9a82-decb2027c139.png)
If you look closely you can see that the antialiasing is poorly managed especially top-left.

But using my PNG image above and displaying it on a black background, this is how it **should** appear:
![test2_b](https://github.com/AngusJohnson/Image32/assets/5280692/8fdc4648-e95e-4528-83d4-263f079bcf14)

Here's a test application that I'm very confident will render transparent images correctly
Create a new VCL application and just add an OnPaint event:
```
uses
  img32, img32.Fmt.BMP, img32.Fmt.PNG;

procedure TForm1.FormPaint(Sender: TObject);
var
  img: TImage32;
  rec: TRect;
begin
  rec := self.ClientRect;
  img := TImage32.Create(rec.Width, rec.Height);
  img.Clear(clBlack32);
  img.CopyToDc(canvas.Handle, 0,0);
  img.LoadFromFile('c:\temp\test2.png');
  img.CopyToDc(canvas.Handle, 100,100);
  img.LoadFromFile('c:\temp\test2.png');
  img.Resampler := rBicubicResampler;
  img.Scale(2.5);
  img.CopyToDc(canvas.Handle, 100,200);
  img.Free;
end;
```

![test2_app](https://github.com/AngusJohnson/Image32/assets/5280692/ac2b2ca6-a227-4627-b6ac-2212656bb379)

**Comment by Escain** [comment]
Hi Angus,

So I could effectively reproduce your code and I made this following modification to show BOTH: working and not-working cases:

````````
procedure TForm1.FormPaint(Sender: TObject);
var
  img: TImage32;
  png: TPngImage;
  rec: TRect;
  bmp: TBitmap;
begin
  rec := self.ClientRect;

  // Some background on the frame, NOT in the image, otherwise we don't have transparency.
  Canvas.Brush.Color := TColor($8F8F6A);
  Canvas.RoundRect(rec.Left, rec.Top, rec.Right, rec.Bottom, 10, 10);

  // Few objects creation
  png := TPngImage.Create();
  img := TImage32.Create(rec.Width, rec.Height);
  bmp := TBitmap.Create();

  //This works without artifacts, but CopyTo/FromBitmap is not used
  img.Clear();
  img.LoadFromFile('img2.png');
  img.Scale(2.7);
  img.CopyToDc(canvas.Handle, 0,0);

  //This also works, but there is no resizing
  png.LoadFromFile('img2.png');
  bmp.assign(png);
  Canvas.Draw(200, 0, bmp);

  //This also works, but CopyToBitmap is not used
  bmp.assign(png);
  img.Clear();
  img.CopyFromBitmap(bmp);
  img.Scale(2.7);
  img.CopyToDc(canvas.Handle, 0,200);

  //This don't work.
  bmp.assign(png);
  img.Clear();
  img.CopyFromBitmap(bmp);
  img.Scale(4);
  img.CopyToBitmap(bmp); // Probable faulty function?
  Canvas.Draw(200, 200, bmp);
  

  // Clean
  img.Free;
  bmp.Free;
  png.Free;
end;

````````

![image](https://github.com/AngusJohnson/Image32/assets/10837802/ef45065b-ab37-492a-91c9-3e32bd3df6e7)

**Comment by AngusJohnson** [comment]
I've just updated TImage32.CopyToBitmap() again in the repository so that it will now blend copy TImage32 onto the bitmap (instead of replacing the bitmap's image). Now the user will have complete control over the bitmap's size and background.

https://github.com/AngusJohnson/Image32/blob/9fc9caaf49804837fd0de644a570dc2364bd8c05/source/Img32.pas#L259-L260

**Comment by Escain** [comment]
Hi Angus,

That is fantastic that you already got one of the two functions solved. Images now looks good in our GUI :-)

If you want to keep the previous functionality, here is something that seems to work (Not heavily tested). However your version seems more versatile.

`````````
class procedure TImage32.ClearBitmapToTransparent(ABitmap: TBitmap);
var
  x, y: Integer;
  p: PRGBQuad;
begin
  if not Assigned(ABitmap) then Exit;

  // Ensure the bitmap format supports transparency
  ABitmap.PixelFormat := pf32bit;

  // Access the raw bitmap data
  ABitmap.Handle;

  // Loop through all pixels
  for y := 0 to ABitmap.Height - 1 do
  begin
    p := ABitmap.ScanLine[y];
    for x := 0 to ABitmap.Width - 1 do
    begin
      p^.rgbReserved := 0;
      p^.rgbRed := 0;
      p^.rgbGreen := 0;
      p^.rgbBlue := 0;
      Inc(p);
    end;
  end;

  ABitmap.Modified := True;
end;

procedure TImage32.CopyToBitmap(bmp: TBitmap);
begin
  if Assigned(bmp) then
  begin
    bmp.SetSize(Width, Height);
    bmp.PixelFormat := pf32bit;
    bmp.AlphaFormat := afDefined;
    ClearBitmapToTransparent(bmp);
    CopyToBItmap(bmp, dstLeft, dstTop);
    CopyToDc(bmp.Canvas.Handle, dstLeft, dstTop, HasTransparency);
  end;
end;
````````

**Comment by AngusJohnson** [comment]
I'm commenting on this rather old thread to acknowledge that there _was_ also a bug TImage32.CopyToBitmap (which I've just fixed). When saving images with no transparency, they were being saved to stream as 24bpp images though incorrectly using [bitfields](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-bitmapinfoheader). Evidently on 16bpp and 32bpp should use BI_BITFIELDS, though _most_ software just ignores bitfields when loading 24bpp images.
