### ISSUE TITLE
Typos in Package

### ISSUE THREAD

**Issue by PeterPanino** [AngusJohnson/Image32#38]
There are several typos in the Package, for example:

![image](https://github.com/AngusJohnson/Image32/assets/5140376/31f6eadc-c73f-4e55-a7fa-160984842aeb)

**Comment by AngusJohnson** [comment]
I've checked the repository and can't see a problem. Could you please be more specific?

**Comment by tomwiel** [comment]
This is no Image32 issue. I've seen exactly this effect with various packages.
The Delphi IDE sometimes modifies text of package files in the source editor.
