### ISSUE TITLE
Blueish tint on OS-X and Android

### ISSUE THREAD

**Issue by birbilis** [AngusJohnson/Image32#4]
Trying Examples/FMX3/fmx_svg.dpr on OS-X 64-bit target (Intel) I see:
![image](https://user-images.githubusercontent.com/3461504/176065948-97dc7db7-8ef0-4e72-b111-290d0b2aa3b3.png)

following up discussion at
https://github.com/EtheaDev/SVGIconImageList/issues/229
and
https://github.com/EtheaDev/SVGIconImageList/issues/233

**Comment by birbilis** [comment]
note: to easily try the Mac version without setting any paths I temporarily (**didn't push change containing that**) added Image32 units to the demo project as file references
![image](https://user-images.githubusercontent.com/3461504/176066653-39bac4e1-c54c-46d2-ab5b-6a232de4a066.png)

the https://github.com/AngusJohnson/Image32/pull/3 sets up a .groupproj to easily build and try demos without setting any paths, but that works out of the box with Windows target only, haven't figured out how to make it work for non Windows targets without having to pull in needed library units as references at respective demo projects

**Comment by birbilis** [comment]
the latest commit at the above PR, that is
https://github.com/AngusJohnson/Image32/pull/3/commits/5c9c083feb3ea87ae25244373122aaccb3d596df
fixes the blueish tint on OS-X

![image](https://user-images.githubusercontent.com/3461504/176067405-98bbacad-9fda-4b8f-9b93-2824d2beca45.png)

**Comment by birbilis** [comment]
also checked Android version with this fix

had to revert System Files to default for the Libraries at the demo project
![image](https://user-images.githubusercontent.com/3461504/176068449-76f31337-f7cc-49ee-b705-939f01608c59.png)

![image](https://user-images.githubusercontent.com/3461504/176068523-bf4f078d-cc60-4dd5-959e-8b47c101afb6.png)

having set up a keystore I could then build for Android and after deploying I get an APK
![image](https://user-images.githubusercontent.com/3461504/176068749-31f637d6-85e3-4899-b3eb-0aa4e19babdf.png)

that I can upload to BrowserStack for interactive testing:
![image](https://user-images.githubusercontent.com/3461504/176069021-eaee2015-6f06-401c-b76c-98c17324888a.png)

and seems I get the same tint on Android so I will probably have to remove the color swap for Android too:
![image](https://user-images.githubusercontent.com/3461504/176069525-41da5bdb-a790-4bca-b8b5-d059e2fb74c9.png)

**Comment by birbilis** [comment]
indeed removing the color swap for Android too at Img32.SVG.Core.pas in function UTF8StringToColor32 fixes the blueish tint there too:
![image](https://user-images.githubusercontent.com/3461504/176070993-0d7c9a00-f7e7-4068-8a7b-e46cb83fbf4b.png)

added a new commit to the PR #3 for the Android fix

**Comment by AngusJohnson** [comment]
I'm closing this Issue because I can't duplicate the color problems that George is reporting.
And without others reporting similar issues I'm not sure just how widespread this issue is (and how much time/effort I need to devote to solving it).
