### ISSUE TITLE
(out of topic) Simple Sudoku

### ISSUE THREAD

**Issue by enigma131** [AngusJohnson/Image32#47]
I see no section for the game, the best one found on y side...
The game is still playable on modern Windows editions, but F1 shortcut is no more working due to hlp format changing for Vista+.
To have access to the tips help, you have to done about, then access to your web site, thanks to the browser http to https redirection.
My question:
Did you plan to rework the game for better using on W10 + ?

**Comment by AngusJohnson** [comment]
> Did you plan to rework the game for better using on W10 + ?

No. Sorry.

**Comment by enigma131** [comment]
Ok thanks, can we consider the game as abandonware ?
The home page have some broken links too.
