### ISSUE TITLE
FR: SVG Image element

### ISSUE THREAD

**Issue by tomwiel** [AngusJohnson/Image32#49]
When comparing SVG renderers, I've found that Image32 SVG is in many regards better than others, but the SVG [Image element](https://www.w3.org/TR/2011/REC-SVG11-20110816/struct.html#ImageElement) is missing. It would be very useful to have drawing if the xlink:href attribute points to an embedded base64-encoded image (would remove the need to use the Direct2D SVG api): [Data Uri](https://en.wikipedia.org/wiki/Data_Uri).

**Comment by AngusJohnson** [comment]
There are lots of things I'd _like_ to do with SVG, including rewriting it (because the code is messy and not very well thought out).
However, I'm very occupied with another project so I doubt I'll be doing much with this library except simple and important fixes for several months at least. So, while your request is very reasonable, I'm unlikely to consider implementing it for some time. Sorry.

**Comment by tomwiel** [comment]
Thank you. I don't know what parts could need a rewrite, but the result is already impressive...

**Comment by AngusJohnson** [comment]
OK, in the zip file below, I've just added in limited support for images in SVG files.
Images must be **embedded** (based64 encoded) in the SVG. 
Also, only embedded JPG and PNG images are supported, and external images will not be rendered.
This needs a little more testing before I upload to the repository.
[Img32_draft2.zip](https://github.com/AngusJohnson/Image32/files/14594825/Img32_draft2.zip)

**Comment by tomwiel** [comment]
Yes, the first version already works (tested with registered TPngImage, TjpegImage)
Some limitations found:  image-draw inside of rotated svg; and if image is declared in defs-tag (like [this](https://upload.wikimedia.org/wikipedia/commons/d/d3/35_mm_angle_of_view_vs_focal_length.svg)). (probably known)

**Comment by AngusJohnson** [comment]
> Some limitations found.

Yep, thanks. Try the latest revision.

**Comment by tomwiel** [comment]
The additions have helped a lot. Do you have also plans for affine transformation of the element-image?

**Comment by AngusJohnson** [comment]
> The additions have helped a lot. Do you have also plans for affine transformation of the element-image?

No. Sorry.
