### ISSUE TITLE
Cannot compile the Lazarus demo: "No matching implementation for interface method"

### ISSUE THREAD

**Issue by rchastain** [AngusJohnson/Image32#5]
Hello!

I cannot compile the Lazarus demo.

```
Img32.pas(112,20) Error: No matching implementation for interface method "_Release:LongInt; CDecl;" found
```

Lazarus 2.3.0, FPC 3.3.1, Linux 64.

I would like to help but unfortunately I never use interfaces and have zero knowledge on that topic. Please could you fix that issue?

**Comment by AngusJohnson** [comment]
Bonjour Roland.
Yes, I need to update the `uses` clause in main.pas.
The reference to `Img32.Clipper` should be changed to `Img32.Clipper2`.
The demo then compiles with any further issues for me (using Lazarus 2.0.12, FPC 3.2.0).
I'll try to update the repository soon.

**Comment by rchastain** [comment]
Thank you for your answer.

There are other problems. I could fix some of them, but not all. I wonder if the library, in its current state, is compatible with Linux. I see several things that are Windows-only.

I believe that we can close the issue? I will give another try to the demo when I have a Windows computer under the hand.

Regards.

Roland

**Comment by AngusJohnson** [comment]
> There are other problems. I could fix some of them, but not all. 

OK, I'm sorry to hear that, though I'm keen to know what they are/were.
And I'll certainly understand if you don't want to persist. 
But if you're prepared to give it another go here's a likely fix:

In `Img32.pas` (in lines 112 and following)
```
  TInterfacedObj = class(TObject, IInterface)
  public
  {$IFDEF FPC}
    function  _AddRef: Integer;
      {$IFNDEF WINDOWS}cdecl{$ELSE}stdcall{$ENDIF};
    function  _Release: Integer;
      {$IFNDEF WINDOWS}cdecl{$ELSE}stdcall{$ENDIF};
    function QueryInterface(
      {$IFDEF FPC_HAS_CONSTREF}constref{$ELSE}const{$ENDIF} iid : tguid;
      out obj) : longint;
      {$IFNDEF WINDOWS}cdecl{$ELSE}stdcall{$ENDIF};
  {$ELSE}
    function  _AddRef: Integer; stdcall;
    function  _Release: Integer; stdcall;
    function  QueryInterface(const IID: TGUID; out Obj): HResult; stdcall;
  {$ENDIF}
  end;
```
(and lines ~3300 and following)

```
{$IFDEF FPC}
function TInterfacedObj._AddRef: Integer;
  {$IFNDEF WINDOWS}cdecl{$ELSE}stdcall{$ENDIF};
begin
  Result := -1;
end;
//------------------------------------------------------------------------------

function TInterfacedObj._Release: Integer;
  {$IFNDEF WINDOWS}cdecl{$ELSE}stdcall{$ENDIF};
begin
  Result := -1;
end;
//------------------------------------------------------------------------------

function TInterfacedObj.QueryInterface(
  {$IFDEF FPC_HAS_CONSTREF}constref{$ELSE}const{$ENDIF} iid : tguid;
  out obj) : longint;
begin
  if GetInterface(IID, Obj) then Result := 0
  else Result := E_NOINTERFACE;
end;

{$ELSE}

function TInterfacedObj._AddRef: Integer; stdcall;
begin
  Result := -1;
end;
//------------------------------------------------------------------------------

function TInterfacedObj._Release: Integer; stdcall;
begin
  Result := -1;
end;
//------------------------------------------------------------------------------

function TInterfacedObj.QueryInterface(const IID: TGUID;
  out Obj): HResult;
begin
  if GetInterface(IID, Obj) then Result := 0
  else Result := E_NOINTERFACE;
end;
{$ENDIF}

```

> I wonder if the library, in its current state, is compatible with Linux. I see several things that are Windows-only.

I'm hoping it is Linux compatible though, as I've said above, I don't currently have linux installed to test it.

> I believe that we can close the issue? 

I will if you don't wish to continue.

**Comment by rchastain** [comment]
Thank you for the code. I will try it at once.

Yes, I am prepared to give it another go, of course.

**Comment by rchastain** [comment]
Applied your patch. Error solved.

Next problem here:

```pascal
// Img32.pas 
function HslToRgb(hslColor: THsl): TColor32;
  // ...
begin
  // ...
  x := c * (255 - abs((hsl.hue mod 85) * 6 - 255)) div 255; // <--- "Can't determine which overloaded function to call"
```

I solved it like this:

```pascal
var
  //...
  c, x, m, a: Integer;
begin
  // ...
  a := (hsl.hue mod 85) * 6 - 255;
  x := c * (255 - abs(a)) div 255;
```

**Comment by rchastain** [comment]
Next problem. Lazarus tries to compile _Img32.FMX.pas_.

I noticed this line:

```
// Img32.Layers.pas, line 469
{$IFNDEF MSWINDOWS} uses Img32.FMX;{$ENDIF} 
```

I tried this:

```
{$IFNDEF FPC}{$IFNDEF MSWINDOWS} uses Img32.FMX;{$ENDIF}{$ENDIF}
```

But the compiler still tries to compile _Img32.FMX_. I will continue to investigate.

**Comment by AngusJohnson** [comment]
Hopefully the latest commit helps. 🤞🙏.

**Comment by rchastain** [comment]
Thank you for the two commits.

Next problem (sorry). :)

```
main.pas(119,47) Error: Identifier not found "DpiAware"
main.pas(129,29) Error: Identifier not found "DPIAware"
main.pas(279,23) Error: Identifier idents no member "CopyToDc"
```

**Comment by AngusJohnson** [comment]
> Next problem (sorry). :)

No, it's me that's sorry. 
Thanks for you patience and thanks for your help too.
I'll try and fix it tonight, but it's close to my bedtime, so unless I find the fix quickly, I'll attend to it tomorrow morning.

**Comment by AngusJohnson** [comment]
I've updated and greatly simplified the Lazarus demo (see attached) and I'm hoping it'll now compile in Linux too. The only thing I'm slightly conderned about is whether `TBitmap.Scanline` is supported in Linux.
[LAZARUS.zip](https://github.com/AngusJohnson/Image32/files/9215108/LAZARUS.zip)
.

**Comment by rchastain** [comment]
Thank you for your work and congratulations. It compiles and works!

I had to do this correction (_img32.pas_ lines 2686 and 2713):

```
    pxDst := {img}self.PixelRow[i];
```

I had to remove these three lines in _main.pas_, line 55:
```

{$IFNDEF MSWINDOWS}
  //bkColor  := SwapRedBlue(bkColor);
  //penColor := SwapRedBlue(penColor);
  //txtColor := SwapRedBlue(txtColor);
{$ENDIF}
```

That's all!

I have the impression that the result on the screen is not what it should be, but in any case it is pretty. :)

![lazarusdemo01](https://user-images.githubusercontent.com/13957204/181703285-cb8b18de-62d2-4d85-b724-0f24913ff987.png)

**Comment by AngusJohnson** [comment]
> have the impression that the result on the screen is not what it should be,

LOL, no! 😜🤪. But I'm encouraged that we're close. 👍

**Comment by rchastain** [comment]
Old televisions used to look like that sometimes when they were not correctly adjusted. :)

When you have solved the bug, you should remember how it was done, and keep it as special effect. :)

**Comment by AngusJohnson** [comment]
> When you have solved the bug, you should remember how it was done, and keep it as special effect. :)

Actually it's not unlike an interim image in cleartype construction where text is stretched out into red green and blue stripes before it's de-stretched.

**Comment by AngusJohnson** [comment]
I'm hoping the latest changes I've just pushed to the repository will fix the above issues. 
However, unrelated to Linux, I'm aware that resizing the SVG in this Demo App can on occasions cause exceptions that I'm investigating, but confident it'll be an easy fix.

**Comment by rchastain** [comment]
Yes it works (and looks very nice).

![image32-lazarus-demo-linux](https://user-images.githubusercontent.com/13957204/181870732-d641f229-bd54-4ede-a860-d0e398f1fe32.png)

**Comment by AngusJohnson** [comment]
Yay! And thank you for all your helpful feedback.

**Comment by AngusJohnson** [comment]
> However, unrelated to Linux, I'm aware that resizing the SVG in this Demo App can on occasions cause exceptions that I'm investigating, but confident it'll be an easy fix.

Found and fixed (in the latest repository commit).

**Comment by rchastain** [comment]
Yes, test successful here too. Bravo!
