### ISSUE TITLE
Png file shows only part of the SVG file

### ISSUE THREAD

**Issue by andre2007** [AngusJohnson/Image32#51]
I tried this coding to convert a SVG file to PNG:

``` delphi
uses Img32, Img32.Fmt.SVG, Img32.Fmt.PNG;
...
//change image format from SVG to PNG
img := TImage32.Create(800,600);
img.LoadFromFile('drawing.svg');
img.SaveToFile('drawing.png');
img.Free;
```

The SVG file looks like this in Chrome Webbrowser:

![image](https://github.com/AngusJohnson/Image32/assets/1451047/2d73ae81-593a-4528-a9bb-2c551978a649)

But the PNG file only shows this, independent of the provided pixel or any scale... methods I am calling:

![image](https://github.com/AngusJohnson/Image32/assets/1451047/51d1c27e-7fa3-4e7e-820a-3296e5bc5b86)

 The SVG file you can find in the attached zip file. What do I wrong?
[drawing.zip](https://github.com/AngusJohnson/Image32/files/14546941/drawing.zip)

I use Delphi 10.2 and Image32 version 4.3

**Comment by AngusJohnson** [comment]
The SVG reader doesn't currently support nested SVG images.

**Comment by andre2007** [comment]
Thanks for the info. Yes, other libraries also have issues displaying this file. I will try now Skia4Delphi or Direct2D.

**Comment by AngusJohnson** [comment]
Try this ... still a draft version as I haven't had time to extensively test it.
[Img32_draft.zip](https://github.com/AngusJohnson/Image32/files/14586844/Img32_draft.zip)

**Comment by andre2007** [comment]
Thank you so much for your incredible work. It looks great also with other more complex music sheets. I cannot spot any issues.
