### ISSUE TITLE
Delphi 12.1 compilation for IOS and Android error

### ISSUE THREAD

**Issue by Fab8573** [AngusJohnson/Image32#53]
Hello,

Problem with 64 bits compilation in Delphi 12.1  ?

`unit 
 Img32.SVG.Core
function Base64Decode(const str: PAnsiChar; len: integer; memStream: TMemoryStream): Boolean;

...
memStream.SetSize((len div 4 * 3) - extra);
...

[DCC Error] Img32.SVG.Core.pas(348): E2251 Ambiguous overloaded call to 'SetSize'
  System.Classes.pas(1238): Associated method : procedure TMemoryStream.SetSize(const Int64);
  System.Classes.pas(1239): Associated method : procedure TMemoryStream.SetSize(LongInt);

On IOS 64 and Android 64

**Comment by AngusJohnson** [comment]
Hopefully fixed now.
