### ISSUE TITLE
Missing JtBevel 

### ISSUE THREAD

**Issue by shineworld** [AngusJohnson/Image32#57]
In the last repository Image32.Clipper2 requires for jtBevel which does not exists in Clipper.pas, neither in other repository Clipper.

**Comment by shineworld** [comment]
The main issue is that I've either Image32 and graphics32 and Image32 uses Clipper loads graphics32 Clipper.pas instead of image32 which is different. Software unit collision.

**Comment by andersmelander** [comment]
`jtBevel` is defined in the version of `Clipper.Offset.pas` included with both Image32 and Graphics32:

https://github.com/AngusJohnson/Image32/blob/1011780aef8ab78b71b36fb972fd75b7fe3e88ba/source/Clipper2/Clipper.Offset.pas#L21

https://github.com/graphics32/graphics32/blob/a16e1cfeca9c66f050ebdee6c2218bfeb72668d8/Source/Clipper.Offset.pas#L21

The version of Clipper2 in Graphics32 is older than the one in Image32. I'm not sure if that is the cause of your problem. Actually, what _is_ the error you are getting?

> This happens when two packages have the same file name in the source path which is different.

Yes, that is a problem but it shouldn't be possible to have two different (design-time) packages containing the same unit in the first place. Unless the unit contains `{$WEAKPACKAGEUNIT ON}` - which it doesn't in this case.

**Comment by AngusJohnson** [comment]
> In the last repository Image32.Clipper2 requires for jtBevel which does not exists in Clipper.pas, neither in other repository Clipper.

I've updated the Clipper2 library and fixed this. 
But what happens in Graphics32 is out of my control as I'm no longer actively supporting Graphics32.
