### ISSUE TITLE
Latest git push is not compilable

### ISSUE THREAD

**Issue by shineworld** [AngusJohnson/Image32#6]
I'm moving from sourceforge project to new github project.
Many new features, fix and improvements seems to be at now available.

But, cloning last code (https://github.com/AngusJohnson/Image32/commit/96a24213e344b6e6d2ceee1cf1ec261b2a8522f7)
the compilation of packages with Sydney 10.4.1 (just to know what I use for), get a lot of missing files and missing options
on project.

dpk are not enought to rebuild a project because missing of any dproj settings as well as list of units prefix.
So a import Graphics, is not enough, you have to add Vcl prefix in options or use Vcl.Graphics in unit import.

In dpk are requested Clipper files different than source projects and also SVG writer is missing.

Save dproj for your delphi version is a starting point, IDEs automatically promote to upper versions of Delphi.
Try to git clone your library in a new folder, change tools library to that and recompile all.
Don't miss to delete ANY library .dcu present in your PC to avoid a direct link to already compiled dcu in some path.

**Comment by AngusJohnson** [comment]
I've uploaded a number of fixes and tested almost all the sample apps again just now in Delphi 10.4 and Delphi 7 and Lazarus. They all* compile and run without problems in Windows. I've also recently tested the FMX files on my Android phone, though not in the last week or two. 

If you're still having problems, you'll need to be morst specific as to what these are. 

*Except those sample apps that can't run

**Comment by shineworld** [comment]
Certainly :)

I am trying to create a VM with state of the art Sydney + Libraries that I used to create a really big project and through an archived VM will allow me to support the project in the future by simply reopening the VM.

To start with, I created a vmWare virtual machine with brand new W10.
I installed Delphi 10.4.1 + patches, the same ones I use in my main W10 machine, and started re-installing all the libraries I use, about 40 of them, including Image32.

Since I am on a new machine, the VM, I am also moving all the libraries to the latest versions.

On the main PC I use a very old version of Image32, but on this VM I git the project from github to try the latest one.

The whole procedure can be seen in this video: https://youtu.be/suqWpDT9Lz0

When opening a DPK Sydeny automatically "recreates" the dproj file where there are all the library project settings including shortcuts for libraries so that Vcl.Graphics can be loaded even omitting the Vcl prefix (see video).

In the Img32_Library.dpk library project there are uses of unavailable source files and I tried to "patch" it using those available in the package but of course it was just an extreme attempt.
Also in the Clipper directory there are requests for files that have been renamed.

Probably somewhere in your PC there are the corresponding DCUs left, for the requested files, and so the compiler, even not finding the PASs still manages to proceed, but on an empty machine, without ever having installed and compiled the previous versions of Img32 the thing does not work.

Probably during the git commint some file that is present in your HD is not added and hence the failure to compile in a clean environment.

I hope I have helped you.

**Comment by AngusJohnson** [comment]
Thanks, I'll certainly have another look. 
(It might take me a few days as I'm currently occupied with other things.)

**Comment by AngusJohnson** [comment]
OK, I've uploaed new *.dproj files for the examples that _should_ fix this. 🙏🤞

**Comment by idw-git** [comment]
> 3\. Since I'm not familiar with the code I don't know where and how (i.e. TRUE vs. FALSE) to initialize it: Outside or inside of the _for i := 0 to High(paths) do_ loop?

Ok, looked into this again, since the compiler says "not used" when inserting it in any other place down below I decided to insert  _ascending := false;_ right at the start of the procedure on line 703, doesn't look to me that it has a real effect on the outcome other than muting the compiler. 

					Michael

-- 
PGP Key ID (RSA 2048): 0xC45D831B
IERenderer's Home <https://www.pmpgp.de/renderer/History.htm>
S/MIME Fingerprint: 94C6B471 0C623088 A5B27701 742B8666 3B7E657C

**Comment by AngusJohnson** [comment]
Thanks Michael for the very helpful feedback.
I'll look at and fix this very soon. Cheers A.

**Comment by idw-git** [comment]
Great, thanks a lot, just checked your SVG sample application and really like the simplicity of usage!

**Comment by AngusJohnson** [comment]
Hi again Michael.
I've just uploaded numerous fixes to the repository.

> 1. First attempt complains about a missing _Img32.Clipper.dcu_ file: Turns out that _Img32.Clipper.pas_ is missing from the ZIP archive, but using _Img32.Clipper**2**.pas_ instead (which _exists_ in the archive) fixes it.

Hopefully fixed now.

> 2. Next complaint is about _Img32.SVG.Writer.dcu_ missing which actually doesn't come with the archive as _Img32.SVG.Writer.pas_ at all so I commented out the respective uses clause entry in the Img32_Library project file auto-created from the DPK file by Delphi.

Hopefully fixed now (I've at least temporarily removed Img32.SVG.Writer.pas).

> 3. After building the now compilable package I'm getting a _not initialized_ warning for the local _ascending_ variable in _Clipper.Engine_'s AddPathsToVertexList() line 771. Since I'm not familiar with the code I don't know where and how (i.e. TRUE vs. FALSE) to initialize it: Outside or inside of the _for i := 0 to High(paths) do_ loop?

This is a compiler bug because all paths do initialize `ascending`.

> PS: Forgot two more: _Img32_Library.dpk_ has two invalid entries: _ClipperCore in '..\Clipper\ClipperCore.pas'_ and _ClipperOffset in '..\Clipper\ClipperOffset.pas'_ reference two non-existing files, they should read _Clipper[.]Core in '..\Clipper\Clipper[.]Core.pas'_ and _Clipper[.]Offset in '..\Clipper\Clipper[.]Offset.pas'_.

These should now be fixed too.

**Comment by idw-git** [comment]
> I've just uploaded numerous fixes to the repository.

Thanks a lot, Angus, installs good now! I've found another issue and have a feature request which I'm going to open up in separate threads. 

					Michael

-- 
PGP Key ID (RSA 2048): 0xC45D831B
IERenderer's Home <https://www.pmpgp.de/renderer/History.htm>
S/MIME Fingerprint: 94C6B471 0C623088 A5B27701 742B8666 3B7E657C
