### ISSUE TITLE
SVG: Stroke geometry does not fully respect transform

### ISSUE THREAD

**Issue by tomwiel** [AngusJohnson/Image32#62]
The found issue is caused in TShapeElement.DrawStroke().
SVG (and common APIs) demand that CTM affects strokes just like geometric shapes.
For example, under nonuniform scale or skew, the visual stroke-width should be varying.
(For authors, this is also needed to preserve gaps between lines and other objects regardless of scene-transform.)
Correct draw of affine circle in browser:
![affineCircle](https://github.com/AngusJohnson/Image32/assets/33182253/74c7c4e6-3b0a-43ab-bea4-676422dfec74)

**Comment by AngusJohnson** [comment]
```
  img := TImage32.create(300,300); 
  img.LoadFromFile('c:\temp\circles.svg');
  img.SaveToFile('c:\temp\circles.png');
  img.Free;
```
![circles](https://github.com/AngusJohnson/Image32/assets/5280692/fb485006-034c-4590-a5e5-3b28176993e6)

I see the problem now :).
In fact I see 2 problems here. The other one is the SVG element's width & height aren't being used to scale the viewbox, hence why I pre-scaled the image (to 300 x 300) as I've done above.

**Comment by AngusJohnson** [comment]
Hopefully fixed now.
Try this  ...

![circles](https://github.com/AngusJohnson/Image32/assets/5280692/e80257c8-89b4-4de1-b4b1-01b3ab444234)

**Comment by tomwiel** [comment]
Very impressive, thanks!
