### ISSUE TITLE
Use Img32 in a "VCL" dll ?

### ISSUE THREAD

**Issue by zedalaye** [AngusJohnson/Image32#63]
Hello,

When I compile my DLL that requires Img32 and Img32.FMT.PNG, the PNG file format seems not registered.

It looks like it's due to the test to detect whether Firemonkey is available :

```
{$ELSEIF declared(FireMonkeyVersion) OR DEFINED(FRAMEWORK_FMX)}
  {$DEFINE USING_FMX}
{$ELSE}
  {$DEFINE USING_VCL}
  {$DEFINE USING_VCL_LCL}
{$IFEND}
```

What causes `{$IF declared(FireMonkeyVersion) OR DEFINED(FRAMEWORK_FMX)}` to be true ? Maybe a require somewhere ?

Thanks for your help

**Comment by AngusJohnson** [comment]
It seems to me the problem is how you're compiling your DLL, and not in the Image32 library.
Evidently when compiling your alleged VCL DLL, the compiler is detecting either FireMonkeyVersion or FRAMEWORK_FMX.
