### ISSUE TITLE
antialiasing issues when using imagepanel to Scaling

### ISSUE THREAD

**Issue by ckok77** [AngusJohnson/Image32#7]
I noticed the usage of imagepanel in your example (svg.dpr), but the same aliasing appears when zooming, how can I keep its sharpness, I tried to redraw, but it seems that the pixels have become larger, Is scaling impossible? Finally, thank you very much for your contribution, this is excellent work

**Comment by AngusJohnson** [comment]
The image panel displays raster images and zooms these raster images so I **expect** you to see pixelation there.
To avoid raster scaling while zooming with the TImagePanel control, you'll need to implement the OnZooming event and reload the SVG image using the new (scaled) dimensions making sure you pre-size the Image (property) appropriately.

**Comment by ckok77** [comment]
thank u very very much! I will try this way!:)
