### ISSUE TITLE
Duplicate Constants in Color List

### ISSUE THREAD

**Issue by LingamYoni** [AngusJohnson/Image32#79]
https://github.com/AngusJohnson/Image32/blob/6f2fdf846c5c1e1e98db95eee7cf35beb98b91fb/source/Img32.pas#L68
I noticed that some constants in the color list are duplicated:

```pascal
// custom gray colors
clDarkGray32 = TColor32($FF505050);
clDarkGrey32 = TColor32($FF505050);
// clGray32   = TColor32($FF808080);
// clSilver32 = TColor32($FFC0C0C0);
clLiteGray32 = TColor32($FFD3D3D3);
clLiteGrey32 = TColor32($FFD3D3D3);
clPaleGray32 = TColor32($FFE0E0E0);
clPaleGrey32 = TColor32($FFE0E0E0);
clDarkBtn32  = TColor32($FFE8E8E8);
clBtnFace32  = TColor32($FFF0F0F0);
clLiteBtn32  = TColor32($FFF8F8F8);
```

Specifically, the following pairs are duplicates:

- `clDarkGray32` and `clDarkGrey32`
- `clLiteGray32` and `clLiteGrey32`
- `clPaleGray32` and `clPaleGrey32`

Could you please confirm if this duplication is intentional? If not, it would be helpful to remove the duplicates to avoid confusion.

**Comment by AngusJohnson** [comment]
It's intentional, and accommodates both English and American spellings.
