### ISSUE TITLE
Linux JPG/PNG support

### ISSUE THREAD

**Issue by TomasEm** [AngusJohnson/Image32#83]
Hi,
is there any easy possibility to make JPG/PNG supported under Linux command line application?
Thanks

**Comment by AngusJohnson** [comment]
Include `Img32.FMX`.

**Comment by TomasEm** [comment]
Hi, Img32.FMX using 
  FMX.Platform,
  FMX.Types,
  FMX.Surfaces,
  FMX.Graphics,

which is not found for commandline application :(

**Comment by AngusJohnson** [comment]
The no, there is no native support for image formats other than `BMP`. Sorry.
