### ISSUE TITLE
Resource Hacker

### ISSUE THREAD

**Issue by Neustradamus** [AngusJohnson/Image32#92]
Dear @AngusJohnson,

Thanks for your work since a long time.

Can you add Resource Hacker on GitHub?
- http://www.angusj.com/resourcehacker/

Thanks in advance.

**Comment by Neustradamus** [comment]
@AngusJohnson: Why have you closed my ticket?

**Comment by AngusJohnson** [comment]
> @AngusJohnson: Why have you closed my ticket?

Because your question has nothing to do with the Image32 library.

**Comment by Neustradamus** [comment]
@AngusJohnson: It is because there is no Resource Hacker repository.
I request you if you have looked the text.

**Comment by Neustradamus** [comment]
@AngusJohnson: I wish you a Happy New Year 2025!

Can you reply to my inital question?

Thanks in advance.
