### ISSUE TITLE
Range Error with this file

### ISSUE THREAD

**Issue by carloBarazzetta** [AngusJohnson/Image32#96]
Hello Angus, I've obtain a Range Error (enabling Range Check Error in compiler) with this file in previous version (committed on 18/08/2024).
![falkland-islands](https://github.com/user-attachments/assets/d890cb99-a464-49ca-aefd-e27a89c60294)

**Comment by andersmelander** [comment]
@carloBarazzetta  I would imagine that Angus would at least like the call stack at the point where the error occurs, so he has something to work from. Ditto for you AV problem.
If you install and enable madExcept then that will provide a bug report with all the details.

**Comment by carloBarazzetta** [comment]
Thank you very much!
Please @AngusJohnson make a new "release" when you consider a version "stable", so I can adopt the new official release for my components.
